spring.mvc.async.request-timeout=600000
server.port=8081
spring.data.mongodb.uri=mongodb://admin:uet%402026@112.137.129.218:27017/iot_agriculture?authSource=admin
spring.data.mongodb.auto-index-creation=false
